AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: A SAM application with an API Gateway and Lambda function that writes to MariaDB
Resources:
  LudibasquetApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: "'GET,POST,OPTIONS,PUT'"
        AllowHeaders: "'Content-Type,Authorization'"
        AllowOrigin: "'*'"
      DefinitionBody:
        openapi: 3.0.1
        info:
          title: LudibasquetApi
          version: 1.0.1
        paths:
          /registrar-incripcio:
            post:
              x-amazon-apigateway-integration:
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${HandleTeamInscription.Arn}/invocations
                httpMethod: POST
                type: aws_proxy
          /registration:
            get:
              x-amazon-apigateway-integration:
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${HandleTeamInscription.Arn}/invocations
                httpMethod: POST
                type: aws_proxy
  HandleTeamInscription:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.12
      CodeUri: ./src
      Timeout: 20
      Policies:
        - AWSLambdaBasicExecutionRole
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - rds-data:ExecuteStatement
                - rds-data:BatchExecuteStatement
              Resource: "*"
      Environment:
        Variables:
          DB_ENDPOINT: ADD YOUR DB ENDPOINT HERE
          DB_NAME: ADD YOUR DB NAME HERE
          DB_USER: ADD YOUR DB USER HERE
          DB_PASSWORD: ADD YOUR DB PASSWORD HERE
          ACCOUNT_SID: ADD YOUR TWILIO ACCOUNT SID HERE
          AUTH_TOKEN: ADD YOUR TWILIO AUTH TOKEN HERE
          SENDER_PHONE: ADD YOUR TWILIO SENDER PHONE HERE
          CONTENT_SID: ADD YOUR TWILIO CONTENT SID HERE
          FRONTEND_URL: ADD YOUR FRONTEND URL HERE
Outputs:
  ApiUrl:
    Description: API Gateway URL
    Value:
      Fn::Sub: https://${LudibasquetApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/
