AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: A SAM application with an API Gateway and Lambda function that writes to MariaDB

Resources:
  LudibasquetApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: "'GET,POST,OPTIONS,PUT'"
        AllowHeaders: "'Content-Type'"
        AllowOrigin: "'*'"
      DefinitionBody:
        openapi: 3.0.1
        info:
          title: LudibasquetApi
          version: 1.0.1
        paths:
          /registrar-incripcio:
            post:
              x-amazon-apigateway-integration:
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${HandleTeamInscription.Arn}/invocations
                httpMethod: POST
                type: aws_proxy

  HandleTeamInscription:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.12
      CodeUri: ./src
      Policies:
        - AWSLambdaBasicExecutionRole
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - rds-data:ExecuteStatement
                - rds-data:BatchExecuteStatement
              Resource: "*"
      Environment:
        Variables:
          DB_ENDPOINT: TODO
          DB_NAME: TODO
          DB_USER: TODO
          DB_PASSWORD: TODO

Outputs:
  ApiUrl:
    Description: "API Gateway URL"
    Value: !Sub "https://${LudibasquetApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
