AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A SAM application with an API Gateway and Lambda function that writes to MariaDB
Resources:
  LudibasquetApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: '''GET,POST,OPTIONS,PUT'''
        AllowHeaders: '''Content-Type,Authorization'''
        AllowOrigin: '''*'''
      DefinitionBody:
        openapi: 3.0.1
        info:
          title: LudibasquetApi
          version: 1.0.1
        paths:
          /registrar-incripcio:
            post:
              x-amazon-apigateway-integration:
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${HandleTeamInscription.Arn}/invocations
                httpMethod: POST
                type: aws_proxy
          /enviar-notificacio:
            post:
              x-amazon-apigateway-integration:
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${SendWA.Arn}/invocations
                httpMethod: POST
                type: aws_proxy
          /inscripcio:
            get:
              x-amazon-apigateway-integration:
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${HandleTeamInscription.Arn}/invocations
                httpMethod: POST
                type: aws_proxy
          /authorize-wa:
            post:
              x-amazon-apigateway-integration:
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${AuthorizeWA.Arn}/invocations
                httpMethod: POST
                type: aws_proxy
  HandleTeamInscription:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.12
      CodeUri: ./src/handle_inscription
      Timeout: 10
      Policies:
        - AWSLambdaBasicExecutionRole
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - rds-data:ExecuteStatement
                - rds-data:BatchExecuteStatement
              Resource: '*'
      Environment:
        Variables:
          DB_ENDPOINT: dummy-endpoint
          DB_NAME: dummy-db
          DB_USER: dummy-user
          DB_PASSWORD: dummy-password
          ACCOUNT_SID: dummy-sid
          AUTH_TOKEN: dummy-token
          SENDER_PHONE: dummy-phone
          CONTENT_SID: dummy-content
          FRONTEND_URL: dummy-url
    Metadata:
      BuildMethod: python3.12
  SendWA:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.12
      CodeUri: ./src/send_wa
      Timeout: 15
      Policies:
        - AWSLambdaBasicExecutionRole
        - Version: '2012-10-17'
      Environment:
        Variables:
          ACCOUNT_SID: dummy-sid
          AUTH_TOKEN: dummy-token
          SENDER_PHONE: dummy-phone
          CONTENT_SID: dummy-content
    Metadata:
      BuildMethod: python3.12
  AuthorizeWA:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.12
      CodeUri: ./src/authorizer
      Timeout: 10
      Policies:
        - AWSLambdaBasicExecutionRole
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - rds-data:ExecuteStatement
                - rds-data:BatchExecuteStatement
              Resource: '*'
      Environment:
        Variables:
          DB_ENDPOINT: dummy-endpoint
          DB_NAME: dummy-db
          DB_USER: dummy-user
          DB_PASSWORD: dummy-password
          ACCOUNT_SID: dummy-sid
          AUTH_TOKEN: dummy-token
          SENDER_PHONE: dummy-phone
          CONTENT_SID: dummy-content
          FRONTEND_URL: dummy-url
          SECOND_LAMBDA_NAME: send-WA
    Metadata:
      BuildMethod: python3.12
  FitxesUploader:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.12
      CodeUri: ./src/fitxes_uploader
      Timeout: 10
      Policies:
        - AWSLambdaBasicExecutionRole
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - rds-data:ExecuteStatement
                - rds-data:BatchExecuteStatement
              Resource: '*'
      Environment:
        Variables:
          BUCKET_NAME: dummy-bucket
    Metadata:
      BuildMethod: python3.12
