FROM amazon/dynamodb-local

USER root

RUN yum update -y

RUN yum install -y gcc-c++ make
RUN curl -sL https://rpm.nodesource.com/setup_20.x | bash -
RUN yum install -y nodejs

WORKDIR /app

RUN npm install @aws-sdk/client-dynamodb

COPY init_DB.mjs /app/
COPY docker-entrypoint.sh /app/

RUN chmod +x /app/docker-entrypoint.sh

ENTRYPOINT ["/app/docker-entrypoint.sh"]
