package main

import "fmt"

func showHelp() {
	fmt.Println("Tournament Management System - Development Helper")
	fmt.Println()
	fmt.Println("Usage: go run cmd/dev/main.go [COMMAND]")
	fmt.Println()
	fmt.Println("Development Commands:")
	fmt.Println("  start     Start development environment")
	fmt.Println("  stop      Stop development environment")
	fmt.Println("  restart   Restart development environment")
	fmt.Println("  logs      View logs (optional: service name)")
	fmt.Println("  reset     Reset database (delete all data)")
	fmt.Println("  connect   Connect to database CLI")
	fmt.Println("  status    Show environment status")
	fmt.Println()
	fmt.Println("Production Commands:")
	fmt.Println("  start-prod     Start production environment")
	fmt.Println("  stop-prod      Stop production environment")
	fmt.Println("  restart-prod   Restart production environment")
	fmt.Println("  logs-prod      View production logs")
	fmt.Println("  status-prod    Show production status")
	fmt.Println()
	fmt.Println("General:")
	fmt.Println("  help      Show this help message")
	fmt.Println()
	fmt.Println("Examples:")
	fmt.Println("  go run cmd/dev/main.go start")
	fmt.Println("  go run cmd/dev/main.go start-prod")
	fmt.Println("  go run cmd/dev/main.go logs db")
	fmt.Println("  go run cmd/dev/main.go connect")
	fmt.Println()
	fmt.Println("Environment Setup:")
	fmt.Println("  Development: Copy env.dev.example to .env.dev")
	fmt.Println("  Production:  Copy env.prod.example to .env.prod.local and edit")
	fmt.Println()
	fmt.Println("Hot Reloading:")
	fmt.Println("  - Air automatically rebuilds on file changes")
	fmt.Println("  - Source code is mounted for live development")
	fmt.Println("  - Check logs to see rebuild progress")
}
